### ISSUE TITLE
Sprint 1 - Documentação - TAP

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#10]
# Descrição
**Iniciar** a produção do _TAP_ (Termo de abertura do projeto)

- História de usuário
    -  Eu, como estudante da Universidade de Brasília, quero poder entender melhor a proposta, as equipes, os custos, os objetivos e os riscos envolvidos na execução deste projeto para melhor compreender o processo de início do mesmo.

# Tarefas
- [x] Determinar um _template_ para ser seguido
- [x] Iniciar a tabela de histórico de versões
- [x] Inserir uma tabela com todas as equipes e seus respectivos papéis
- [x] Realizar a descrição do projeto

# Critérios de aceitação
- [x] O documento deve estar no formato markdown
- [x] O documento deve ter sido revisado
- [x] O documento deve ter sido inserido no repositório do projeto

**Comment by Matheuspleal** [comment]
# Links úteis

- https://github.com/fga-eps-mds/Projeto01/issues/6#issuecomment-1022324492
- https://fga-eps-mds.github.io/2021.1-AlligaBot/2021/08/02/termo-de-abertura-do-projeto/
- https://fga-eps-mds.github.io/2019.2-Acacia/#/project_charter

**Comment by gabrielm2q** [comment]
- Exemplo de Termo de Abertura de Projeto: [TAP do projeto CheeryUP](https://fga-eps-mds.github.io/2020.2-CheeryUP/#/./wiki/TAP)

**Comment by Matheuspleal** [comment]
Foi definido, por semelhança maior com a necessidade dos grupos envolvidos no projeto 1, que o _template_ utilizado será o do _Alligabot_

**Comment by Matheuspleal** [comment]
# Documento base pra criação do _markdown_
https://docs.google.com/document/d/1_9-X-CblCYwo7ZmUfFw72Dz0bw7IIFr5tCEc3oMVMyY/edit?usp=sharing

**Comment by gabrielm2q** [comment]
Por se tratar do mesmo tópico, as "Partes Interessadas" (Usuários e Equipes) presentes no Termo de Abertura do Projeto serão similares às descritas no tópico 3 do Documento de Visão (descrição dos usuários e envolvidos).

**Comment by gabrielm2q** [comment]
Os requisitos de alto nível serão definidos posteriormente após decisão dos grupos.

**Comment by guibrbs** [comment]
Os demais riscos serão adicionados posteriormente, conforme a evolução do projeto.

**Comment by gabrielm2q** [comment]
A versão inicial do TAP foi inserida no repositório.

**Comment by guigudf** [comment]
@Matheuspleal como o documento já foi revisado pelo @oCaioOliveira, estarei marcando a opção nos Critérios de aceitação, favor fechar a issue.

**Comment by Matheuspleal** [comment]
@guigudf O @oCaioOliveira revisou apenas o 1° tópico ou o documento como um todo ?? Se o documento como um todo tiver sido revisado, irei fechar a issue

**Comment by oCaioOliveira** [comment]
@Matheuspleal @guigudf calma gente kakaka, só consegui ler um tópico, e deixei ele revisado para quem continuasse, desculpa aí se não ficou claro.

**Comment by oCaioOliveira** [comment]
O Termo de Aberturo do Projeto foi revisado até o 5° tópico, sem erros de digitação, coerente com o planejamento da equipe, únicas observações a serem feitas é que existem algumas frases em latim (eu acho) que eu não entendi e apenas lembrar de colocar o nome do projeto como INDICAA (ideia do @Matheuspleal).

**Comment by guigudf** [comment]
@Matheuspleal retirar as duas siglas que não seram usadas no projeto (Covid e H3N2) e como o caio falou, o histórico de versões está com erros na duas últimas versões

**Comment by gabrielm2q** [comment]
Retirei as siglas COVID e H3N2 e atualizei a versão do projeto.

**Comment by ticu-stack** [comment]
O termo de abertura foi revisado do quinto ao último tópico e se adequa ao modelo previamente planejado pela equipe, estando claro, sucinto e informativo. 
Nesse sentido, tendo em vista que o tópico 6 será preenchido futuramente, só observei um tópico que poderia ser alterado conforme as normas ABNT. O tópico 10 das referências.

**Comment by guigudf** [comment]
@Matheuspleal favor fechar a issue.

**Comment by Matheuspleal** [comment]
Documento revisado conforme as observações da @ticu-stack e do @oCaioOliveira, as futuras mudanças serão feitas no decorrer do projeto.
