### ISSUE TITLE
Sprint 1 - Documentação - Inicio do Documento de Arquitetura

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#11]
# Descrição
**Iniciar** a produção do documento de arquitetura

- História de usuário
    -  Eu, como estudante da Universidade de Brasília, quero poder entender melhor a proposta, as ferramentas, os objetivos e os riscos envolvidos na execução deste projeto para melhor compreender o processo de início do mesmo.

# Tarefas
- [x] Determinar um _template_ para ser seguido @guigudf 
- [x] Iniciar a tabela de histórico de versões @guigudf 
- [x] Realizar a descrição dos Objetivos @Mateusvff 
- [x] Realizar a descrição do Escopo do projeto @guigudf 
- [x] Definir o  Padrão Arquitetural a ser seguido
- [x] Exemplificar as Tecnologias utilizadas 
- [x] Exemplificar o Diagrama de Pacotes
- [x] Definir as Metas do Projeto @PedroSiq 
- [x] Anotar as possíveis Restrições do Projeto @Eruel6 

# Critérios de aceitação
- [x] O documento deve ter todos os tópicos solucionados
- [x] O documento deve estar no formato markdown
- [x] O documento deve ter sido revisado
- [x] O documento deve ter sido inserido no repositório do projeto @guigudf

**Comment by guigudf** [comment]
Versão inicial criada no repositório

**Comment by guigudf** [comment]
O **Padrão Arquitetural**, as **Tecnologias Utilizadas** e o **Diagrama de Pacotes** serão discutidos e definidos futuramente, após reunião com todos os membros dos grupos

**Comment by guigudf** [comment]
@ticu-stack você poderia revisar o documento de arquitetura por favor?

**Comment by gabrielm2q** [comment]
- No tópico 1.2 do documento (segunda linha) a sigla "UNB" poderia ser substituída por "UnB", conforme apresentado na tabela de siglas. Além disso, a grafia de "professores" apresenta erro ("professoraes"). 

- Ainda no tópico 1.2, talvez seja interessante substituir "Universidade de Brasília - Campus Gama" por "Universidade de Brasília - Faculdade do Gama", porém fica a critério dos autores. 

- Além disso, talvez seja interessante substituir o trecho "será mais simples" (tópico 1.2, quarta linha) por "serão mais simples", haja vista que este se refere à múltiplas atividades.

- No escopo do projeto são informadas as aplicações do mesmo para os alunos. Talvez seja interessante já substituir "alunos" por "membros da coordenação", haja vista que estes serão os principais usuários da plataforma (a priori).

- No tópico 3.1, talvez seja interessante substituir o trecho "amostragem dos indicadores" por outro, mas isso fica a critério dos autores.

No mais, o Documento de Arquitetura foi muito bem desenvolvido, sendo bem explicativo e conciso, cumprindo com o proposto na _issue_.
