### ISSUE TITLE
Sprint 2 - EAP - Documentação

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#15]
# Descrição
Criar a estrutura inicial do documento de _Estrutura Analítica do Projeto_

# Tarefas 
- [x] Criar a estrutura inicial do documento
- [x] Inserir uma tabela de versionamento

# Critérios de aceitação
- [x] O documento ter sido revisado
- [x] O documento ter sido postado

**Comment by Matheuspleal** [comment]
Tomei como modelo o EAP do grupo [Acácia](https://fga-eps-mds.github.io/2019.2-Acacia/#/wbs).

**Comment by Matheuspleal** [comment]
# Estrutura analítica do projeto

## Histórico de versões

| Data | Versão | Autor(es/as) |
|------|--------|--------------|
|05/02/2022|0.1|Matheus Pimentel Leal|

## Siglas

| Sigla | Descrição |
|-------|-----------|
|  UnB  | Universidade de Brasília |
|  FGA  | Faculdade do Gama |
|  MVP  | Minimum Viable Product |

## 1. Introdução
Este documento visa demonstrar de forma visual, o projeto. Em forma de um diagrama que relaciona todas as características necessárias para a entrega do _MVP_, ou Mínimo produto viável.

## 2. Diagrama
(A inserir...)

**Comment by Matheuspleal** [comment]
O que acham desta versão acima?

**Comment by gabrielm2q** [comment]
Acredito que cumpre o proposto. Talvez seja interessante remover a descrição "ou Mínimo produto viável" da última linha da introdução, haja vista que MVP já é descrito na tabela de siglas.
No mais, bom documento :+1:

**Comment by Matheuspleal** [comment]
Todos os itens levantados pela revisão do documento foram atendidos, e o documento foi upado para o repositório.
