### ISSUE TITLE
Sprint 2 - Documentação - Requisitos Funcionais e Não Funcionais

### ISSUE THREAD

**Issue by oCaioOliveira** [fga-eps-mds/Projeto01#17]
# Descrição

Definir os requisitos do projeto, tanto funcionais como não funcionais.

# Tarefas

Realizar os seguintes passos:

- [x] Definir os Requisitos Funcionais.
- [x] Definir os Requisitos Não Funcionais.
- [ ] Todas as equipes revisarem e estarem de acordo com todos os requisitos.

# Critérios de aceitação

- [ ] Postagem do Documento de Requisitos.
- [ ] Caso seja necessário explicar os Requisitos.

**Comment by MorettiGS** [comment]
Para auxiliar na criação do Documento de Requisitos, seguem alguns links úteis:

Explicações:
* [O que são requisitos](https://analisederequisitos.com.br/requisitos-funcionais-e-nao-funcionais/);
* [O que é e como fazer um Documento de Requisitos](https://analisederequisitos.com.br/documento-de-requisitos-de-software/);
* [Curta explicação sobre as etapas da criação do documento](https://opencadd.com.br/engenharia-de-requisitos-conheca-todas-as-etapas-do-processo/);
* [Modelo geral do documento](https://www.inf.ufsc.br/~jean.hauck/guias/29110/Norma%20ISO%2029110%20Perfil%20de%20Entrada%20B%C3%A1sico/guidances/examples/documento_especificao_de_requisitos_2CFB343D.html);

Exemplos:
* [Documento de requisitos - SIGA Ensino](https://www2.ufjf.br/diavi//files/2016/07/DocumentosdeRequisitosdoSistema.pdf)
    * [Link para o site](https://portalsiga.es.gov.br/contexto).
* [Documento de Requisitos - SILCRED](http://docs.fct.unesp.br/docentes/dmec/rogerio/ES_II/DR2.pdf)
* [Documento de Requisitos - GEDAI](http://www2.dc.ufscar.br/~gedai/documentos/Relatorios/Documentacao-Site.pdf)

**Comment by AdneMoretti** [comment]
Para auxiliar no documento de requisitos, segue uma breve descrição dos requisitos funcionais e não funcionais e alguns links interessantes.

A análise e o levantamento de requisitos são fundamentais para o desenvolvimento do software, com esta fase, é possível definir o que o cliente deseja e as funcionalidades que o produto deve ter.
### Requisitos funcionais
São as funcionalidades de um software, solicitadas pelo cliente em questão.
### Requisitos não funcionais:
Associados a segurança, usabilidade, velocidade. Coisas que os clientes não vão exigir, porém, são necessidades para o produto.

## Links
[Elaboração de requisitos e fases](https://medium.com/lfdev-blog/como-escrever-requisitos-de-software-de-forma-simples-e-garantir-o-m%C3%ADnimo-de-erros-no-sistema-app-74df2ee241cc)
[Requisitos funcionais e não funcionais](https://www.youtube.com/watch?v=YLd6AWKVyas)

**Comment by guibrbs** [comment]
Complementando, segue alguns links úteis que possam esclarecer melhor a ideia de um requisito funcional ou não funcional através de exemplos.
## Links
[Engenharia de Requisitos](http://www.facom.ufu.br/~bacala/DAW/Aula02-1%20-%20Engenharia%20de%20Requisitos.pdf)
[O que são requisitos funcionais e não funcionais?](https://codificar.com.br/requisitos-funcionais-nao-funcionais/#Requisitos_Funcionais) (Especialmente os tópicos 6 e 7, onde tratam exemplos)

**Comment by oCaioOliveira** [comment]
O documento com os requisitos funcionais e não funcionais está sendo atualizado no seguinte arquivo:
https://unbbr-my.sharepoint.com/:w:/g/personal/190085291_aluno_unb_br/EVfZbpzPunhMrZpPo8N1QJQBTq_efAUTo_wj91_kZGSgCw?e=4Pbvjc

**Comment by gabrielm2q** [comment]
Adicionei algumas sugestões de requisitos funcionais no documento (RFs 12, 13, 14 e 15).

**Comment by PedroSiq** [comment]
No dia 13/02, os POs de cada grupo (@PedroSiq, @AdneMoretti e @laurapinos) se reuniram para revisar o documento de funcionalidades do Software, na qual foram feitos comentários sobre cada requisito funcional e não funcional definido previamente em reunião dos grupos. Resta apenas um alinhamento final com os arquitetos do projeto para finalizar a versão 1.0 do Documento de Requisitos.

**Comment by guigudf** [comment]
@PedroSiq, @AdneMoretti e @laurapinos, favor subir o documento de requisitos (finalizado em reunião do dia 14/02) para o repositório e fechar a issue.
