### ISSUE TITLE
Abertura do gitpages de projeto

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#20]
# Descrição
Fazer a configuração inicial do Gitpages

# Tarefas
- [x] Criação do Gitpages

# Critérios de aceitação
- [x] Pagina do gitpages funcionando 
- [x] Outra pessoa conseguir acessar a url

**Comment by guibrbs** [comment]
Suspeito que falta a criação e inserção de um arquivo index.html no diretório do projeto. Irei adicionar e realizar testes quanto ao funcionamento.

**Comment by guibrbs** [comment]
Fiz o resolução do problema, inicialmente adicionei um index.html a branch main do projeto para testar e mudei em settings > code and automation > Pages > Source e coloquei a Branch main. Posteriormente, verifiquei a criação do index.html pelo @guigudf na branch gh-pages, porém dentro das configurações citadas anteriormente, estava endereçado dentro de /root, sendo que o arquivo html estava em /docs. Então alterei de /root para /docs e a página veio a funcionar. Estarei removendo o index.html da branch main que eu criei como teste, deixando exclusivamente para a branch gh-pages.

**Comment by Matheuspleal** [comment]
Tentarei acesso ao gitpages pelo meu celular e pelo desktop.
