### ISSUE TITLE
Adicionar  "Issue templates" no repositório

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#22]
# Descrição
Fazer o template para criação de issues

# Tarefas
- [x] Criação do template para criação de issues

# Critérios de aceitação
- [x] Template Criado
- [x] Template adicionado ao repositório

**Comment by oCaioOliveira** [comment]
Template de issues foi criado e adicionado ao repoitório. Segue o link para encontrá-lo:
https://github.com/fga-eps-mds/Projeto01/tree/main/docs/templates

**Comment by guigudf** [comment]
@oCaioOliveira tenta abranger mais um pouco o template esse um link do projeto do alligabot pode ajudar https://github.com/fga-eps-mds/2021.1-AlligaBot/blob/main/.github/ISSUE_TEMPLATE/custom.md

**Comment by guigudf** [comment]
além desses tópicos tem a seleção da sprints e separação entre os épicos tb

**Comment by LeticiaAires** [comment]
@oCaioOliveira li o documento com as alterações e acredito que esteja de acordo com os objetivos e expectativas da issue.
Minha única observação é quanto à parte dos épicos, de resto tá ótimo.

**Comment by oCaioOliveira** [comment]
Template de Issues foi atualizado e se encontra no mesmo link citado acima, faltando apenas um tópico para ser fechado, no caso o tópico da separação entre os épicos.

**Comment by oCaioOliveira** [comment]
@guigudf Acredito estar de acordo e finalizado, irei fechar a issue.
