### ISSUE TITLE
Adicionar "Contributing" no repositório

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#23]
# Descrição
Fazer o template para contribuição do projeto

# Tarefas
- [x] Criação do documento de contribuição

# Critérios de aceitação
- [x] Documento Criado
- [x] .MD adicionado ao repositório

**Comment by guigudf** [comment]
Link que pode se usado como base pra criação do documento 
https://github.com/fga-eps-mds/2021.1-AlligaBot/blob/main/docs/_posts/2021-08-16-como-contribuir.md

**Comment by Matheuspleal** [comment]
@guigudf O documento foi revisado. Alteração que sugiro:
- No tópico de criação de issues, acredito que pode ser dito para utilizar o [_issue template_](https://github.com/fga-eps-mds/Projeto01/blob/main/.github/ISSUE_TEMPLATE/sprint--x-----tipo-da-issue-----o-que-ser--feito-.md) também
