### ISSUE TITLE
Adicionar "Description" no repositório 

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#25]
# Descrição
Fazer o descrição do projeto

# Tarefas
- [x] Criação da descrição do projeto 

# Critérios de aceitação
- [x] Descrição do projeto apresentada no repositório
- [x] Texto revisado e aprovado

**Comment by guigudf** [comment]
adicionar o site do gitpages na descrição "https://fga-eps-mds.github.io/Projeto01/"

**Comment by guigudf** [comment]
@Matheuspleal favor, revisar o texto

**Comment by Matheuspleal** [comment]
O texto feito foi revisado e está de acordo com os ideais do grupo.
