### ISSUE TITLE
Templates de commit

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#29]
# Descrição
Criar templates para realização de commits no repositório do projeto, visando melhor organização

# Tarefas
- [x] Discussão sobre possíveis templates
- [x] Definição do template

# Critérios de aceitação
- [x] O template de commit ter sido criado
- [ ] O template de commit ter sido revisado

**Comment by guigudf** [comment]
Template de commits do AlligaBot
https://github.com/fga-eps-mds/2021.1-AlligaBot/blob/main/docs/_posts/2021-08-18-commits.md

**Comment by Matheuspleal** [comment]
> Template de commits do AlligaBot https://github.com/fga-eps-mds/2021.1-AlligaBot/blob/main/docs/_posts/2021-08-18-commits.md

Acredito que a política de commits deles parece ser muito boa e extremamente aplicável ao nosso projeto.

O commit de exemplo deles:
        
    git commit -m ":bulb:(#02): botão na página inicial"

**Comment by Matheuspleal** [comment]
Posso realizar a criação do documento de templates para commit ?

**Comment by guigudf** [comment]
Pode sim

**Comment by Matheuspleal** [comment]
Adicionei o documento e já utilizei a nova política de commits, favor revisar. @guigudf @LeticiaAires

**Comment by guigudf** [comment]
documento revisado e de acordo com objetivo da issue. Estou fechando a issue
