### ISSUE TITLE
Diagrama do projeto

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#31]
# Descrição
Realizar a criação e revisão do diagrama geral do projeto, conforme feito no [tópico 2 do EAP do projeto _Acácia_](https://fga-eps-mds.github.io/2019.2-Acacia/#/wbs).

# Tarefas
- [x] Definição dos itens pertencentes ao diagrama
- [x] Criação do diagrama

# Critérios de aceitação
- [x] O diagrama estar dentro do padrão definido nos comentários da issue
- [x] O diagrama estar devidamente upado no repositório do projeto
- [x] O diagrama ter sido revisado

**Comment by guigudf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/time-de-desenvolvimento-61fbf381b1fbfb00106daf65/issues/fga-eps-mds/Projeto01/31?planning-poker) with ZenHub @AdneMoretti @Matheuspleal @LeticiaAires

**Comment by RochaCarla** [comment]
Qual o objetivo dessa issue?

**Comment by Matheuspleal** [comment]
Irei atualizar a descrição das issues que não contém ainda.

**Comment by Matheuspleal** [comment]
@RochaCarla Foram adicionadas descrições em todas as issues criadas até então.

**Comment by gabrielm2q** [comment]
Seguem alguns exemplos de diagramas presentes no EAP de outros projetos:
- [EAP do Amika](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/eap)
- [EAP do AlligaBot](https://fga-eps-mds.github.io/2021.1-AlligaBot/2021/08/08/documento-de-estrutura-anal%C3%ADtica/)
- [EAP do FoodCare](https://fga-eps-mds.github.io/2019.2-FoodCare/projeto/eap/)

**Comment by Mateusvff** [comment]
Utilizaremos como referência principal para elaboração do diagrama geral do projeto os modelos de diagrama dos projetos AlligaBot e Acacia com enfoque no AlligaBot. Utilizaremos como ferramenta principal para o desenvolvimento do diagrama o Miro.

**Comment by Mateusvff** [comment]
![Untitled](https://user-images.githubusercontent.com/71900095/154864336-55c49aad-149f-40d7-84de-e82352a2a96e.jpg)

**Comment by Mateusvff** [comment]
Diagrama geral do projeto criado e pronto para revisão

**Comment by MorettiGS** [comment]
Ao meu ver, foi encontrada, no elemento de "Apresentação e filtragem" das "Funcionalidades", uma pequena confusão de concordância de gênero com seus elementos filhos. Para envolver todos eles, talvez seja adequado adicionar, no trecho "Apresentação e filtragem das", artigos que englobem os substantivos masculinos como "cursos" ou "alunos", ou seja, alterar "das" para "das(os)" ou "dos(as)".

Com essa pequena observação à parte, o documento está bem explicativo e desenvolvido, seguindo todos os elementos e seções desejadas. Portanto, excelente trabalho!

**Comment by gabrielm2q** [comment]
Tal erro foi provocado por um "corte" na palavra "informações", de modo que teríamos: "Apresentação e filtragem das informações".
Todavia, está corrigido! Agradeço o feedback!
![diagrama_eap](https://user-images.githubusercontent.com/72149063/155042838-288a1f76-956f-4219-ba87-6e599f380dce.jpg)
