### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#34]
# Descrição
Confecção do protótipo de alta fidelidade, seguindo a ideia inicial que foi proposta pelo protótipo de baixa fidelidade da issue #33 

# Tarefas
- [x] Transferir as ideias obtidas no protótipo de baixa fidelidade para este
- [x] Realizar a confecção do protótipo de alta fidelidade

# Critérios de aceitação
- [x] O protótipo de alta fidelidade estar conforme os padrões exigidos pela disciplina
- [x] O protótipo de alta fidelidade ter sido revisado

**Comment by oCaioOliveira** [comment]
Os integrantes dos grupos se reuniram no dia 17/02 e fizeram uma versão do protótipo de alta fidelidade de acordo com os requisitos do projeto.

## Versão 1.0:

![1](https://user-images.githubusercontent.com/54439337/154601962-6c1324f3-b750-4c2b-89fb-16e542dbc44f.png)
![2](https://user-images.githubusercontent.com/54439337/154601964-42f9ab4d-61da-4dee-88e9-b4e48e1c1e2f.png)
![3](https://user-images.githubusercontent.com/54439337/154601966-e54be364-e64a-41d8-837d-a0d52db2b9d6.png)
![4](https://user-images.githubusercontent.com/54439337/154601968-e90aa3a1-2451-4f6e-9731-d1dea5e9ef6c.png)
![5](https://user-images.githubusercontent.com/54439337/154601969-b5756bd0-43ca-4f1c-9056-31896bfa5b94.png)
![6](https://user-images.githubusercontent.com/54439337/154601970-64d246a8-eb75-427c-8ad1-bc725e5b12fe.png)
![7](https://user-images.githubusercontent.com/54439337/154601949-3819c41d-c67a-4393-98c7-12001341465d.png)
![8](https://user-images.githubusercontent.com/54439337/154601953-14888e62-3c2a-47f2-b494-e755a3606477.png)
![9](https://user-images.githubusercontent.com/54439337/154601955-e35f823e-efeb-4e64-87b3-82cd36ef327e.png)
![10](https://user-images.githubusercontent.com/54439337/154601956-35d69be9-4781-413a-9b93-8be8733ddb96.png)
![11](https://user-images.githubusercontent.com/54439337/154601957-b752840b-2ee2-4fcc-ac19-94ba9181b135.png)
![12](https://user-images.githubusercontent.com/54439337/154601959-44b9a84e-4c5e-4b05-9a84-2b2884f3b532.png)
![13](https://user-images.githubusercontent.com/54439337/154601960-3c833553-63cd-481b-9c24-10d9768977a9.png)

**Comment by oCaioOliveira** [comment]
O Protótipo de Alta Fidelidade precisa ser revisado por alguém que não participou da sua confecção.

**Comment by oCaioOliveira** [comment]
## Exceções do sistema:

![INDICAA (3)](https://user-images.githubusercontent.com/54439337/154602994-827eeab4-cfe7-4462-add0-519dfa6e1e85.png)
![INDICAA (2)](https://user-images.githubusercontent.com/54439337/154602997-d356150f-3bb7-48a2-9d69-541aa239dda3.png)

**Comment by gabrielm2q** [comment]
No tocante a escrita e às ilustrações, o Protótipo de Alta Fidelidade, aparentemente, está bem formulado e consistente com o que é pedido. 
Talvez seja necessário disponibilizar as ilustrações em um arquivo em *markdown*.
Talvez seja interessante detalhar o que é pedido do requisito funcional 14 (RF14), isto é, "O sistema deve permitir que o usuário altere a forma de exibição do horário". Todavia, acredito que isto está a critério de vocês.
No mais, o P. A. F. aparentemente atende a todos os outros requisitos funcionais disponibilizados no documento de requisitos e cumpre com o proposto, ilustrando bem o sistema.

**Comment by guibrbs** [comment]
No dia 22/02 recebemos o feedback da professora Carla e alterações referentes aos gráficos, pesquisa por disciplina e filtros serão feitas.

**Comment by oCaioOliveira** [comment]
De acordo com as sugestões da professora Carla, o protótipo de alta fidelidade foi alterado para sua versão 1.1, ainda seguindo as especificações e requisidos do proejto 01.

## Versão 1.1

![16](https://user-images.githubusercontent.com/54439337/155227990-bccecb60-16ba-4a6b-885f-5bfeb67489cc.png)
![17](https://user-images.githubusercontent.com/54439337/155227995-465ad28f-83b7-4c89-b4c6-1baf35909edd.png)
![18](https://user-images.githubusercontent.com/54439337/155227997-b6a341a9-1258-4485-873e-7757359c2da0.png)
![19](https://user-images.githubusercontent.com/54439337/155228000-99256dfa-4f11-4ac2-ba36-8515b1892438.png)
![20](https://user-images.githubusercontent.com/54439337/155228003-1c33c35a-1531-4254-a30b-0128aa3b7b7f.png)
![21](https://user-images.githubusercontent.com/54439337/155228004-fb46a6ed-ddd9-48b3-b1a4-1addf48bf2d8.png)
![22](https://user-images.githubusercontent.com/54439337/155228006-24178a73-ee14-4528-84b6-ec0409c0362a.png)
![23](https://user-images.githubusercontent.com/54439337/155228010-5ecc5f1c-be2c-44c1-ba2b-4af0b539a4ca.png)
![24](https://user-images.githubusercontent.com/54439337/155228012-ab14f1d9-db9e-4d58-ad48-a80767c5db5f.png)
![25](https://user-images.githubusercontent.com/54439337/155228013-47788f20-bc12-46ce-9d8c-375ed2d07e04.png)
![26](https://user-images.githubusercontent.com/54439337/155228014-31b3e97d-eade-4d2c-9479-6a06a3f2578c.png)

**Comment by guibrbs** [comment]
Documento em markdown dos protótipos adicionado ao repositório.

**Comment by guibrbs** [comment]
Foram feitas alterações em relação ao visual e a adição da logo.

## Versão 1.2
![14](https://user-images.githubusercontent.com/88190414/156658266-fbe5e3e8-5c66-4243-9d0c-d394c9803fc2.png)
![15](https://user-images.githubusercontent.com/88190414/156658267-1ca80183-ed24-47d1-9dae-96ed254618e8.png)
![16](https://user-images.githubusercontent.com/88190414/156658268-58992d0b-b04d-4c87-9a53-3c8e70fe756c.png)
![17](https://user-images.githubusercontent.com/88190414/156658269-b9793751-f0e1-4e91-9311-802e20e1c33b.png)
![18](https://user-images.githubusercontent.com/88190414/156658271-0c9ed543-69bf-46af-b52f-12a8bd6498f0.png)
![19](https://user-images.githubusercontent.com/88190414/156658273-0918ac40-a0b6-4cab-add6-8eb72ae32e72.png)
![20](https://user-images.githubusercontent.com/88190414/156658252-74fe8a2b-146f-48ea-ace3-7c4486c24324.png)
![21](https://user-images.githubusercontent.com/88190414/156658256-fbc0dd29-0e27-4630-b0c5-ea49e004e7e9.png)
![22](https://user-images.githubusercontent.com/88190414/156658258-430d5da6-c714-49bf-9ef4-ce533864d4ed.png)
![23](https://user-images.githubusercontent.com/88190414/156658259-17929ea3-e114-4ec9-8802-86aa3e3f9636.png)
![24](https://user-images.githubusercontent.com/88190414/156658260-4edede74-527c-42f9-b91b-ab5922c1484e.png)
![25](https://user-images.githubusercontent.com/88190414/156658261-f80e9b35-5f08-44de-8d82-a192e5700357.png)
![26](https://user-images.githubusercontent.com/88190414/156658263-1aece59e-0060-428e-bfe0-4217c2d9ed9e.png)
