### ISSUE TITLE
Configuração da pagina inicial do gitpages

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/Projeto01#37]
# Descrição
Fazer a configuração da pagina inicial do Gitpages

# Tarefas
- [x] Criar Menu lateral no Gitpages com os documentos do projeto
- [x] Criar ícone de redirecionamento para o repositório 
- [x] Escrever a descrição do projeto e boas vindas 

# Critérios de aceitação
- [x] Pagina do gitpages funcionando 
- [x] Menu lateral visível
- [x] Redirecionamento funcionando
- [x] Texto aparecendo na página inicial   
- [x] Outra pessoa conseguir acessar a url

**Comment by guigudf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/time-de-desenvolvimento-61fbf381b1fbfb00106daf65/issues/fga-eps-mds/Projeto01/37?planning-poker) with ZenHub @Matheuspleal @guibrbs

**Comment by joaopaulob3** [comment]
- [Um pouco da documentação do GitPages](https://docs.github.com/pt/pages/getting-started-with-github-pages/about-github-pages)
*(olhem o menu à esquerda)*

**Comment by guigudf** [comment]
@Matheuspleal a página inicial já está com a apresentação do projeto e redirecionamento para o repositório, favor verificar se consegue acessar

**Comment by Matheuspleal** [comment]
@guigudf Tudo correto, o acesso foi feito com sucesso.
