### ISSUE TITLE
Treinamento Git

### ISSUE THREAD

**Issue by oCaioOliveira** [fga-eps-mds/Projeto01#40]
# Descrição
Reunião dos grupos para treinamento das tecnologias específicas decididas pelo time.

# Tarefas
- [x] Treinamento Git

# Critérios de aceitação
- [x] Postagem da gravação do treinamento
- [x] Postagem de um resumo do que foi desenvolvido no treinamento

**Comment by guigudf** [comment]
a aula foi realizada dia 21/02 as 18hrs e pode ser encontrada no [pasta de treinamentos](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/aulas/treinamento_git.md) do repositório
