### ISSUE TITLE
Familiarização com políticas de commit

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#44]
# Tarefas

- [x] Alinhamento geral sobre o template de commit.

# Critérios de aceitação

- [x] Todos os membros estarem atualizados com as políticas de commit.

**Comment by Matheuspleal** [comment]
Em reunião no dia 15/02/2022, os integrantes do grupo 3 foram familiarizados com a nova política de commits.

**Comment by LeticiaAires** [comment]
No dia 15/02/2022 e 17/02/2022, os integrantes do grupo 1 foram familiarizados com o novo modelo de commits por meio de avisos no whatsapp.

**Comment by joaopaulob3** [comment]
Para quem estiver em dúvida, os templates (modelos padrão que deverão ser considerados) desenvolvidos estão [aqui](https://github.com/fga-eps-mds/Projeto01/tree/main/docs/templates).

**Comment by Matheuspleal** [comment]
Alterei o link para ir diretamente ao documento de políticas de commit

**Comment by PedroSiq** [comment]
No dia 17/02/2022, os integrantes do grupo 04 foram alinhados com o modelo de padronização dos commits por meio de checagens individuais. Favor fechar a issue.

**Comment by Matheuspleal** [comment]
Todos os membros foram avisados e alinhados com relação às políticas de commit. A partir desta sprint será exigido a política de commits.
