### ISSUE TITLE
Revisar Estrutura Analítica do Projeto

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#46]
# Tarefas
- [x] Revisar o documento de Estrutura analítica do projeto (Após conclusão do Diagrama)
- [x] Completar informações faltantes (Caso aplicável)

# Critérios de aceitação
- [x] Documento atualizado e versão postada no repositório
- [x] Documento revisado

**Comment by gabrielm2q** [comment]
Foi alterada a descrição do EAP anteriormente escrita e foi inserido o diagrama produzido na issue #31. 
Portanto, o documento é passível de revisão.

**Comment by gabrielm2q** [comment]
O diagrama teve um erro de escrita/apresentação corrigido, conforme requisitado na issue #46. Falta apenas a revisão da parte escrita do EAP em si.

**Comment by MorettiGS** [comment]
Primeiramente, em relação ao termo _Minimum Viable Product_ utilizado, poderia ser considerada a adição de sua tradução, para melhor esclarecimento, em algum lugar no documento. Como exemplo, no trecho do tópico de introdução "as atividades necessárias para a entrega do MVP".
Entretanto, penso que essa adição seria completamente opcional, visto que não trará muitas adições ao documento no geral, ficando a critério dos responsáveis considerá-la.

Com relação ao diagrama do projeto em si, o mesmo foi revisado e comentado na _issue_ (#31), como citado no [comentário](https://github.com/fga-eps-mds/Projeto01/issues/46#issuecomment-1047327267) anterior.

Fora isso, o documento foi bem desenvolvido e encontra-se dentro dos padrões desejados. Ótimo trabalho!

**Comment by gabrielm2q** [comment]
Foi adicionada a tradução de MVP na aba de siglas, de modo que qualquer um que buscar o significado do termo já o encontre logo na tabela.
Portanto, documento revisado!
