### ISSUE TITLE
Revisar Documento de Arquitetura

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#47]
# Tarefas
- [x] Revisar o [documento de Arquitetura](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_arquitetura.md) (Após definição dos requisitos)
- [x] Completar informações faltantes (Caso aplicável)

# Critérios de aceitação
- [x] Documento atualizado e versão postada no repositório
- [x] Documento revisado

**Comment by joaopaulob3** [comment]
Fiz algumas alterações inspirado nos documentos do Alligabot e Acácia, mas existem informações que, ao meu ver, só poderemos adicionar após um maior desenvolvimento e progresso no projeto. 
@PedroSiq peço que verifique se mais informações podem ser adicionadas no nosso documento.

**Comment by PedroSiq** [comment]
Documento revisado no dia 21/02, estou de acordo com as mudanças efetuadas e com a possibilidade de futuras novas alterações. No momento, não temos nada de novo a ser acrescentado.
