### ISSUE TITLE
Revisar Documento de visão

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#48]
# Tarefas
- [x] Revisar o [documento de Visão](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_visao.md) (Após definição dos requisitos)
- [x] Completar informações faltantes (Caso aplicável)

# Critérios de aceitação
- [x] Documento atualizado e versão postada no repositório
- [x] Documento revisado

**Comment by LeticiaAires** [comment]
O Documento de Visão foi revisado e atende aos objetivos estabelecidos com sua criação.
