### ISSUE TITLE
Revisar Termo de Abertura do projeto

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#49]
# Tarefas
- [x] Revisar o [Termo de Abertura do Projeto](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/termo_de_abertura.md)(Após definição dos requisitos)
- [x] Completar informações faltantes (Caso aplicável)

# Critérios de aceitação
- [x] Documento atualizado e versão postada no repositório
- [x] Documento revisado

**Comment by gabrielm2q** [comment]
Primeiramente, acredito que na tabela de siglas o termo "INDICAA" já possa ser declarado como "nome dado ao projeto", isto é, é interessante retirar o termo "provisório", haja vista que "INDICAA" já foi usado em vários documentos como sendo um nome oficial (acredito eu).

Na seção de "partes interessadas", os alunos/estudantes são colocados em primeiro lugar na tabela. Como o foco, salvo engano, é auxiliar os coordenadores de curso a tomarem decisões com base nos dados disponibilizados, talvez seja interessante colocar os coordenadores em primeiro lugar na tabela (ainda que a ordem não seja necessariamente importante), de modo a dar destaque ao público-alvo principal do software.
*p.s.: caso venha a ser informado que o foco da aplicação são os alunos, o trecho acima pode ser desconsiderado.*

Na descrição de DevOps, talvez seja interessante ressaltar a parte de "entrega e integração contínuas" ao final da frase, isto é, adicionar o termo "integração".

Na parte de "Estratégias de Comunicação", talvez seja interessante adicionar o Jitsi como meio de comunicação com a professora e com os monitores em treinamentos (conforme ocorrem nas aulas e no treinamento dado pelo monitor).

No mais, ao meu ver, o TAP atende ao esperado e está muito bem desenvolvido!

**Comment by MorettiGS** [comment]
As devidas alterações referentes ao [comentário](https://github.com/fga-eps-mds/Projeto01/issues/49#issuecomment-1047168862) anterior foram realizadas com sucesso, efetivando a revisão do documento.

Com relação à seção de partes interessadas, foi alterada a ordem dos elementos como solicitado, porém essa alteração ainda poderá ser revertida, como citado.

Obrigado pelo feedback!
