### ISSUE TITLE
Sprint 0 - Pesquisas - Metodologias ágeis

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#5]
# Descrição
Pesquisar sobre as metodologias ágeis que serão utilizadas durante a execução do projeto

# Tarefas
Estudar as seguintes metodologias:

- [x] SCRUM
- [x] XP (Extreme Programming)
- [x] Kanban

# Critérios de aceitação

- [x] Postagem da ata de revisão da sprint
- [x] Atualização da tabela de conhecimentos

**Comment by gabrielm2q** [comment]
## Kanban
- Apresentação da Metodologia
    - [What is Kanban?](https://www.youtube.com/watch?v=iVaFVa7HYj4) (duração: cerca de 5 minutos): o vídeo apresenta uma breve introdução ao Kanban e a alguns de seus termos, explicando como a metodologia funciona e como ela pode agilizar a realização de atividades durante o desenvolvimento.
    - [14 Reasons to Choose Kanban](https://medium.com/hygger-io/14-reasons-to-choose-kanban-for-software-development-d3ddb420d273) (tempo de leitura: cerca de 7 minutos): o texto apresenta uma breve introdução do Kanban, seguindo com 14 benefícios que este apresenta para o desenvolvimento de software. Em resumo:
        >    Apresentação visual das atividades
        >    Limitação da quantidade de atividades ao mesmo tempo
        >    Melhor ordenação das atividades
        >    Foco nas atividades em andamento
        >    Flexibilidade
- Comparação com o Scrum
    - [Scrum or Kanban](https://medium.com/hygger-io/scrum-or-kanban-whats-the-difference-f8948059e864) (tempo de leitura: cerca de 6 minutos): o texto inicia apresentando o Scrum e o Kanban como sendo duas metodologias ágeis. Em seguida, são apresentados os princípios do Manifesto Ágil. Em suma, o texto apresenta o Kanban como sendo uma metodologia ágil mais flexível e focado nas tarefas a serem feitas no momento. Já o Scrum é apresentado como uma metodologia menos flexível e focado no término das Sprints. As tarefas no Kanban, apesar de possuírem um tempo estimado de duração, não possuem um prazo rígido e fixo como no Scrum, que seria o final da Sprint.
- Conclusão
    -  O Kanban é uma metodologia ágil flexível e eficiente, apresentando uma estrutura visual (composta por quadros) de fácil entendimento e maior fixação. O uso desta permite que a equipe realize as atividades de acordo com seus níveis de prioridade e tenha um número máximo de atividades a serem feitas no momento (o que evita o multitasking, que pode dividir a atenção da pessoa). Dentre as ferramentas que suportam o Kanban, temos o Trello, o Jira e o próprio GitHub.

**Comment by Matheuspleal** [comment]
# SCRUM

## Definição

> SCRUM é um _framework_ leve que ajuda pessoas, times e organizações a gerar valor por meio de soluções adaptativas para problemas complexos.
<br/> O Guia do SCRUM - Ken schwaber e Jeff Sutherland

Resumidamente, o SCRUM requer que um _SCRUM Master_ promova um ambiente onde:

- Um _Product Owner_ ordena o trabalho para um problema complexo em um _Product Backlog_
- O _SCRUM Team_ transforma uma seleção do trabalho em um incremento de valor durante uma _sprint_
- O _SCRUM Team_ e seus _stakeholders_ inspecionam os resultados e se ajustam para a próxima _sprint_
- Repita tudo acima novamente

## Objetivo

O principal objetivo do SCRUM é promover um ambiente organizado e coeso de trabalho, que promova a rapidez, e também, fazer com que todos os membros se sintam Respeitados.

## Transparência, Inspeção e adaptação

- Transparência: Os processos emergentes e o trabalho devem ser visíveis tanto para quem executa o trabalho quanto para quem recebe o trabalho

> A transparência permite a inspeção. A inspeção sem transparência é enganosa e gera desperdício.

- Inspeção: Os artefatos do SCRUM e o progresso em direção às metas acordadas devem ser inspecionados com frequência e diligência afim de detectar variações ou problemas potencialmente indesejáveis.

> A inspeção habilita a adaptação. A inspeção sem adaptação é considerada inútil. Os eventos SCRUM são projetados para provocar mudanças.

- Adaptação: Se algum aspecto de um processo se desviar fora dos limites aceitáveis ou se o produto resultante for inaceitável, o processo que está sendo aplicado ou os materiais que estão sendo produzidos devem ser ajustados.

> A adaptação se torna mais difícil quando as pessoas envolvidas não são empoderadas ou auto-gerenciadas. Espera-se que um _SCRUM Team_ se adapte no momento em que aprende algo novo por meio da inspeção.

## Os valores do SCRUM

- Compromisso
- Foco
- Abertura
- Respeito
- Coragem

> O Scrum Team se _compromete_ a atingir seus objetivos e suportar uns aos outros. Seu _foco_ principal é o trabalho da Sprint para fazer o melhor progresso possível em direção a essas metas. O Scrum Team e seus stakeholders são _abertos_ quanto ao trabalho e os desafios. Os membros do Scrum Team se _respeitam_ quanto a serem pessoas capazes e independentes, e são _respeitados_ como tal pelas pessoas com quem trabalham. Os membros do Scrum Team têm a _coragem_ de, fazer a coisa certa e trabalhar em problemas difíceis.
<br/> O Guia do SCRUM - Ken schwaber e Jeff Sutherland

## SCRUM Team

O SCRUM Team é a unidade fundamental do SCRUM e consiste de um grupo pequeno de pessoas: O _SCRUM Team_.

Ele é composto de:

- Um SCRUM Master
- Um Product Owner
- Developers

## A sprint

São eventos de **duração fixa**, de um mês ou menos, para criar consistência. Uma nova _sprint_ começa imediatamente após a conclusão da _sprint_ anterior

Todo trabalho necessário para atingir a meta do produto, incluindo _Sprint Planning_, _Sprint Review_, _Daily SCRUMS_ e _Sprint retrospective_, acontece dentro de _sprints_

### Durante a _sprint_:
- Nenhuma mudança é feita que coloque em risco a meta da _sprint_
- A qualidade não diminui
- O _Product Backlog_ é refinado conforme necessário
- O escopo pode ser esclarecido e renegociado com o _Product Owner_ conforme mais é aprendido.

## Links úteis:

- https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Portuguese-European.pdf
- https://www.scrum.org/
- https://www.amazon.com.br/SCRUM-fazer-dobro-trabalho-metade/dp/8543107164
- https://pt.wikipedia.org/wiki/Scrum

**Comment by Matheuspleal** [comment]
Issue fechada e tabela de conhecimentos atualizada.

**Comment by Matheuspleal** [comment]
A [Tabela de horários e conhecimentos](https://docs.google.com/spreadsheets/d/1JK9VD2ZH0LRuSzyCv9FFOPxFlodrCBf5-axeVi9_g94/edit#gid=180244969) pode ser vista por qualquer grupo!
