### ISSUE TITLE
Sprint 0 - Pesquisas - Documentações

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/Projeto01#6]
# Descrição
Pesquisar sobre as documentações a serem criadas para a sprint 1

# Tarefas
Pesquisar sobre as seguintes documentações:

- [x] Termo de abertura do projeto
- [x] Documento de visão
- [x] Estrutura analítica do projeto
- [x] Documento de arquitetura
- [x] Roadmap

# Critérios de aceitação
- [x] Postagem da ata de revisão da sprint
- [x] Atualização da tabela de conhecimentos

**Comment by gabrielm2q** [comment]
## Documento de Visão
- Resumo 
    - É um termo que busca apresentar uma visão geral do programa, definindo itens como o escopo do projeto, seu posicionamento, a descrição do público-alvo e uma série de restrições do produto. É importante para facilitar o entendimento do produto e o rumo que este tomará.
- Documentos de Visão - Exemplos
    - [Doc. de Visão - IBM](https://www.ibm.com/docs/pt-br/elm/6.0.5?topic=requirements-vision-document): o texto aborda todos os pontos relevantes para a concepção de um documento de visão, apresentando um breve resumo de cada componente.
    - [Doc. de Visão - Acácia](https://fga-eps-mds.github.io/2019.2-Acacia/#/vision_document);
    - [Doc. de Visão - CheeryUP](https://fga-eps-mds.github.io/2020.2-CheeryUP/#/./wiki/Documents/Documento_de_Visao);
    - [Doc. de Visão - Hortum](https://fga-eps-mds.github.io/2020.2-Hortum/Documento_de_visao/);
    - [Doc. de Visão - Chatbot Nilo](https://github.com/fga-eps-mds/2019.2-Chatbot-Nilo/blob/develop/docs/DocumentoDeVisao.md).

**Comment by AdneMoretti** [comment]
### Documento de Visão
- O documento de visão tem como objetivo apresentar a visão geral do projeto, envolvendo o escopo, a problemática, o propósito e a solução apresentada para o problema, também descreve o que o projeto tem que atender.
- É composto pelos seguintes tópicos:

1. **Introdução**:
 Fornece uma visão geral de todo o documento, é composto pelo escopo, propósito e definições e acrônimos
2. **Posicionamento**: 
Descreve a oportunidade de negócios, instrução do problema e instrução de posição do produto
3. **Descrição dos envolvidos e dos usuários:** 
Descreve todos os envolvidos no processo e suas responsabilidades
4. **Visão geral do produto:** 
Fornece uma visão das capacidades do produto, é composto por Perspectiva do Produto, Funções do Produto, Suposições e Dependências.
5. **Recursos:** 
Descreve brevemente os recursos do produto
6. **Restrições:**
Apresenta as restrições necessárias do produto
7. **Requisitos:**
A lista de requisitos do produto

[Documento de Visão- IBM](https://www.ibm.com/docs/pt-br/elm/6.0.5?topic=requirements-vision-document) : Apresenta todos os tópicos do documento de visão e a descrição de cada um deles.

**Comment by AdneMoretti** [comment]
### Estrutura analítica do projeto:

- A estrutura analítica do projeto é responsável por organizar os objetivos e coisas a serem entregadas com o projeto de forma visual, é o plano de projeto baseado em suas dependências. Divide em partes menores para melhor visualização e gerenciamento.
- Para o desenvolvimento de uma EAP é necessário estabelecer as fases principais e em seguida apresentar as tarefas necessárias para alcançar os resultados.
- Uma EAP pode ser orientada a produtos ou ao ciclo de vida do projeto, e cabe ao gerente optar pelo que melhor se adapta a realidade do projeto
- Deve ser produzida depois que os requisitos e o termo de abertura do projeto já estão bem definidos.
- Essa estrutura é importante pois ajuda a:

1. Definir as atividades necessárias para o desenvolvimento do projeto;
2. Controlar o andamento do projeto;
3. Facilitar a estimar custos, planejar recursos e identificar riscos;

[Exemplo de EAP- Post-Mortem](https://fga-eps-mds.github.io/2019.2-Acacia/#/wbs)
[EAP-euax](https://www.euax.com.br/2018/12/eap-estrutura-analitica-projeto/)
[EAP- artia](https://artia.com/blog/como-fazer-eap-na-gestao-de-projetos/):

**Comment by MorettiGS** [comment]
## Termo de Abertura do Projeto ( TAP )

* Resumo
    *  O Termo de Abertura do Projeto, também chamado de Project Charter, é um documento que formaliza o início de um projeto, conferindo autorização ao gerente de projeto e agrupando todas as informações necessárias para a execução das atividades envolvidas, dessa forma abrindo formalmente o processo de desenvolvimento do mesmo.

* Entre outras, o documento possui como principais as seguintes seções:
    * **Principais responsáveis pelo projeto:** Onde estão citados todos os envolvidos na realização do projeto, geralmente com foco no gerente de projeto;
    * **Descrição:** Uma descrição curta e concisa sobre o que o projeto se trata e quais são suas principais características;
    * **Justificativa:** Um parágrafo com o objetivo de justificar o ínicio do projeto no tempo e condições presentes, geralmente servindo de termômetro caso o mesmo faça parte de uma lista de outros projetos, destacando sua prioridade.
    * **Objetivos e metas do projeto:** Uma lista do que a equipe planeja alcançar com o projeto. Preferencialmente, a escrita dessa seção deve ser de forma específica e objetiva, seguindo o conceito SMART;
    * **Marcos:** Um pequeno texto ou lista contendo as principais e mais importantes entregas do projeto;
    * **Premissas:** Composta de algumas suposições tomadas pela equipe responsável, como afirmações ou hipóteses que se consideram verdadeiras antes do início do projeto;
    * **Restrições:** Algumas limitações e riscos que podem afetar o desenvolvimento do processo ou dos participantes da equipe, alterando ou não o produto final;
    * **Orçamento estimado para o projeto:** Em projetos financiados, essa seção é responsável por apresentar ao patrocinador uma ideia de todos os aspectos financeiros do projeto.

## Links Úteis

* Para melhor detalhamento do processo de criação e dos elementos de um TAP, segue os links utilizados para essa pesquisa, junto a alguns exemplos:
    * [Conceitos, elementos e exemplos - TAP](https://robsoncamargo.com.br/blog/Termo-de-abertura-de-projeto-saiba-tudo-sobre-ele)
    * [Project Charter - O que é e quais são seus elementos?](https://www.laboneconsultoria.com.br/conheca-os-10-elementos-do-project-charter-no-lean-six-sigma/)
    * [TAP - O que é e como montar o seu.](https://artia.com/blog/termo-de-abertura-do-projeto/)
    * [TAP - O que é, como fazer, exemplo.](https://escritoriodeprojetos.com.br/termo-de-abertura-do-projeto)
    * [Exemplo - TAP](https://www.trabalhosgratuitos.com/Humanas/Administra%C3%A7%C3%A3o/Tap-exemplo-898955.html)
    * [Exemplo 2 - TAP](https://www.trabalhosgratuitos.com/Humanas/Administra%C3%A7%C3%A3o/Exemplo-de-Termo-de-Abertura-de-Projetos-TAP-1192759.html)

**Comment by Matheuspleal** [comment]
# Documento de arquitetura

## Definição

> O documento de arquitetura de software fornece uma visão geral de arquitetura abrangente do sistema de software.

## Objetivo

O principal objetivo do documento de arquitetura de software é servir como um meio de comunicação entre o **arquiteto de software** e outros membros da equipe de projeto, com relação a decisões arquiteturalmente significativas tomadas sobre o projeto.

## Afinal, o que é arquitetura de software ?

> A arquitetura de software é uma descrição do sistema que auxilia na compreensão de como o sistema irá se comportar.

Arquitetura é um meio de se obter uma análise antecipada para garantir que a abordagem de design apresentada produzirá um sistema que alcance os requisitos exigidos pelos stakeholders, tais como: Desempenho, segurança, disponibilidade, integridade e flexibilidade. Portanto, uma arquitetura de software consiste na definição de suas camadas, que podem envolver entidades como: componentes de software, aplicativos externos, sistemas legados e propriedades externas

## Por que documentar a arquitetura de software?

A arquitetura do software deve ser documentada por um simples motivo: Por mais perfeita e adequada que seja a sua arquitetura, ela será inútil para outras pessoas e desenvolvedores que não a conhecem e que não podem entendê-la bem o suficiente para manuseá-la.

## Estrutura do documento de arquitetura de software:

- Histórico de revisões
- Introdução
- Representação arquitetural
- Metas e Restrições arquiteturais
- Visão de casos de uso
- Visão lógica
- Visão de implementação
- Referências

## Modelos de documento de arquitetura:

- https://fga-eps-mds.github.io/2020.2-Hortum/Documento_de_arquitetura/
- https://fga-eps-mds.github.io/2021.1-AlligaBot/2021/08/03/documento-de-arquitetura/
- https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document
- https://fga-eps-mds.github.io/2020.1-Ziguen/
- http://www.facom.ufu.br/~flavio/pds1/files/2016-01/Documento%20de%20Arquitetura%20de%20Software%20do%20SPEU%201-Exemplo-RUP.pdf

## Links úteis

- http://www.linhadecodigo.com.br/artigo/3343/como-documentar-a-arquitetura-de-software.aspx
- https://www.cin.ufpe.br/~gta/rup-vc/core.base_rup/workproducts/rup_software_architecture_document_C367485C.html
- https://www.cin.ufpe.br/~gta/rup-vc/core.base_rup/guidances/guidelines/software_architecture_document_F4C93435.html

**Comment by Matheuspleal** [comment]
Issue fechada e tabela de conhecimentos atualizada.

**Comment by Matheuspleal** [comment]
A [Tabela de horários e conhecimentos](https://docs.google.com/spreadsheets/d/1JK9VD2ZH0LRuSzyCv9FFOPxFlodrCBf5-axeVi9_g94/edit#gid=180244969) pode ser vista por qualquer grupo!
