### ISSUE TITLE
Sprint 1 - Documentação - Documento de visão

### ISSUE THREAD

**Issue by oCaioOliveira** [fga-eps-mds/Projeto01#8]
# Descrição

Produzir o documento de visão sobre o projeto.

# Tarefas

Realizar os seguintes passos:

- [x] Analisar documentos de visão de outros projetos e abstrair dicas e pontos chave
- [x] Criar um template para ir adicionando informações ao longo do projeto;
- [x] Definir o escopo do projeto;
- [x] Adicionar informações atuais sobre o projeto;

# Critérios de aceitação

- [x] Postagem da análise de documentos de visão de projetos de outros semestres;
- [x] Postagem do documento de visão;
- [x] Apresentar de onde foram tiradas ideias e inspirações para o documento;
- [x] O documento de visão deve ser revisado por outro grupo e as análises feitas informadas;
- [x] O documento de visão após ser revisado deve ser corrigido e informado;

**Comment by lucasqueiroz23** [comment]
[Análise de documentos de visão passados.pdf](https://github.com/fga-eps-mds/Projeto01/files/7945361/Analise.de.documentos.de.visao.passados.pdf)

**Comment by oCaioOliveira** [comment]
O escopo do projeto foi definido com base nas instruções iniciais dadas pela professora Carla na issue Tema 01 - SIGAA Indicadores, pode ser visualizado no documento de visão que ainda está em desenvolvimento. Segue o link:
https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_visao.md

**Comment by oCaioOliveira** [comment]
Ao longo da semana foi criado um template, baseando-se em projetos da matéria do passado. Todas as informações atuais do projeto foram inseridas e organizadas neste template e as ideias foram referenciadas ao final do documento de visão e na análise de documentos. Segue o link do Documento de Visão:
https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_visao.md

**Comment by MorettiGS** [comment]
Documento revisado por mim e pela @AdneMoretti ( **Grupo 3** ). O documento está bem completo, mas temos as seguintes observações:

* Ao início do segundo parágrafo do tópico 1.3, a utilização da vírgula para separar as palavras "projeto" e "seria" pode ter causado certa estranheza na leitura da frase.

* Ao final do tópico 2.3, há a ocorrência da palavra "quanto" de forma duplicada.

* No tópico 3.1 ( Descrição dos Usuários ), foi inserido na tabela uma descrição para "Outros", mas esses mesmos não foram citados no tópico 3.5 sobre os Perfis dos Usuários. Seria bom incluí-los, caso achem pertinente.

* Ao final do tópico 4.2, há a ocorrência da palavra "matricula", sem seu devido acento agúdo.

* Em ambos os tópicos 5.1 e 5.2, ocorrem possíveis erros de markdown. Imagino que o que está escrito com um asterisco no início deviam ser elementos de uma _bullet list_, mas a formatação está incorreta.

* Ao final do tópico 5.1, há a ocorrência da palavra "disponiveis", sem seu devido acento agúdo.

Fora isso, ótimo trabalho!

@oCaioOliveira  @laurapinos

**Comment by ticu-stack** [comment]
@MorettiGS e @AdneMoretti as devidas alterações referentes à revisão foram realizadas. 

Obrigada!

**Comment by guigudf** [comment]
@oCaioOliveira favor fechar a issue
